# ═══════════════════════════════════════════════════════════════
# Auto-generated by ansys_mesher.py — ISPCC Mesh Probe Pipeline
# Methodology: Zienkiewicz-Zhu (1987, 1992), Babuška-Rheinboldt (1978)
# Insert controls in order — later entries take higher priority
# ═══════════════════════════════════════════════════════════════

import System

# ── Model references ────────────────────────────────────────────
model  = ExtAPI.DataModel.Project.Model
mesh   = model.Mesh
geo    = model.Geometry

# Get first body (extend for multi-body geometry)
try:
    body = geo.Children[0].Children[0]
except:
    body = geo.Children[0]

# ── Geometry helpers ───────────────────────────────────────────
def dist3(ax, ay, az, bx, by, bz):
    return ((ax-bx)**2 + (ay-by)**2 + (az-bz)**2)**0.5

def find_face(cx, cy, cz, tol=10.0):
    """Find face whose centroid is nearest (cx,cy,cz). tol in model units."""
    best, best_d = None, float("inf")
    for f in body.Faces:
        c = f.Centroid
        d = dist3(c.X, c.Y, c.Z, cx, cy, cz)
        if d < best_d:
            best_d, best = d, f
    return best if best_d < tol else None

def find_edge(mx, my, mz, tol=10.0):
    """Find edge whose midpoint is nearest (mx,my,mz)."""
    best, best_d = None, float("inf")
    for e in body.Edges:
        mid = e.StartVertex.Location
        end = e.EndVertex.Location
        c = ((mid.X+end.X)/2, (mid.Y+end.Y)/2, (mid.Z+end.Z)/2)
        d = dist3(c[0], c[1], c[2], mx, my, mz)
        if d < best_d:
            best_d, best = d, e
    return best if best_d < tol else None

def find_vertex(vx, vy, vz, tol=2.0):
    """Find vertex nearest (vx,vy,vz)."""
    best, best_d = None, float("inf")
    for v in body.Vertices:
        loc = v.Location
        d   = dist3(loc.X, loc.Y, loc.Z, vx, vy, vz)
        if d < best_d:
            best_d, best = d, v
    return best if best_d < tol else None

def make_ns(name, ids, entity_type):
    """Create Named Selection from a list of entity IDs."""
    ns   = model.AddNamedSelection()
    ns.Name = name
    sel  = ExtAPI.SelectionManager.CreateSelectionInfo(
               SelectionTypeEnum.GeometryEntities)
    sel.Ids = ids
    ns.Location = sel
    return ns

def make_sizing(ns, h_mm, behavior="Soft", sizing_type="ElementSize"):
    """Add a sizing control on a named selection."""
    sz = mesh.AddSizing()
    sz.Location = ns
    if sizing_type == "ElementSize":
        sz.Type = SizingType.ElementSize
        sz.ElementSize = Quantity(str(round(h_mm, 4)) + " [mm]")
    if behavior == "Hard":
        sz.Behavior = SizingBehavior.Hard
    else:
        sz.Behavior = SizingBehavior.Soft
    return sz

# ════════════════════════════════════════════════════════════════
# Step 1 — Global Body Sizing (baseline, Soft)
# Babuška & Rheinboldt (1978): lower-bound element size for acceptable error
# ════════════════════════════════════════════════════════════════
body_ns = make_ns("ISPCC_Body_Global", [body.Id], "Body")
sz_global = mesh.AddSizing()
sz_global.Location = body_ns
sz_global.Type = SizingType.ElementSize
sz_global.ElementSize = Quantity("5.0000 [mm]")
sz_global.Behavior = SizingBehavior.Soft
print("Step 1 done — global body sizing 5.0000 mm".format(5.0000))

# ════════════════════════════════════════════════════════════════
# Step 2 — Inflation: 2-2-1 B transition from each Pi face
# Zienkiewicz & Zhu (1992): superconvergent patch — layer grading
# 5 total layers: 2 Pi-weighted + 2 mixed + 1 B proper
# ════════════════════════════════════════════════════════════════
# Zone 1 — Π face inflation
face_z1 = find_face(-10.0, 0.0, 10.0)
if face_z1 is not None:
    ns_z1 = make_ns("ISPCC_Pi_Face_1", [face_z1.Id], "Face")
    infl_z1 = mesh.AddInflation()
    infl_z1.Location = ns_z1
    infl_z1.InflationOption = InflationOption.TotalThickness
    infl_z1.TotalThickness = Quantity("10.0000 [mm]")
    infl_z1.NumberOfLayers = 5
    infl_z1.GrowthRate = 1.2
    print("  Zone 1 inflation added")
else:
    print("  [WARN] Zone 1 face not found at centroid (-10.00,0.00,10.00)")

# Zone 6 — Π face inflation
face_z6 = find_face(10.0, 0.0, 10.0)
if face_z6 is not None:
    ns_z6 = make_ns("ISPCC_Pi_Face_6", [face_z6.Id], "Face")
    infl_z6 = mesh.AddInflation()
    infl_z6.Location = ns_z6
    infl_z6.InflationOption = InflationOption.TotalThickness
    infl_z6.TotalThickness = Quantity("10.0000 [mm]")
    infl_z6.NumberOfLayers = 5
    infl_z6.GrowthRate = 1.2
    print("  Zone 6 inflation added")
else:
    print("  [WARN] Zone 6 face not found at centroid (10.00,0.00,10.00)")

print("Step 2 done — inflation from 2 Pi face(s)")

# ════════════════════════════════════════════════════════════════
# Step 3 — Edge Sizing: zone boundary Β entities
# TSA theorem: h_edge = sqrt(h_Pi × h_E) — geometric mean
# Blacker & Stephenson (1991): boundary layer seeding
# ════════════════════════════════════════════════════════════════
# Edge 1 — Pi_E
edge_1 = find_edge(-10.0000, 0.0000, 0.0000)
if edge_1 is not None:
    ns_e1 = make_ns("ISPCC_Edge_1_Pi_E", [edge_1.Id], "Edge")
    make_sizing(ns_e1, 5.0000, behavior="Soft")
else:
    print("  [WARN] Edge 1 not found at midpoint (-10.00,0.00,0.00)")

# Edge 2 — Pi_E
edge_2 = find_edge(-10.0000, 0.0000, 20.0000)
if edge_2 is not None:
    ns_e2 = make_ns("ISPCC_Edge_2_Pi_E", [edge_2.Id], "Edge")
    make_sizing(ns_e2, 5.0000, behavior="Soft")
else:
    print("  [WARN] Edge 2 not found at midpoint (-10.00,0.00,20.00)")

# Edge 3 — Pi_E
edge_3 = find_edge(-10.0000, 10.0000, 10.0000)
if edge_3 is not None:
    ns_e3 = make_ns("ISPCC_Edge_3_Pi_E", [edge_3.Id], "Edge")
    make_sizing(ns_e3, 5.0000, behavior="Soft")
else:
    print("  [WARN] Edge 3 not found at midpoint (-10.00,10.00,10.00)")

# Edge 4 — Pi_E
edge_4 = find_edge(-10.0000, -10.0000, 10.0000)
if edge_4 is not None:
    ns_e4 = make_ns("ISPCC_Edge_4_Pi_E", [edge_4.Id], "Edge")
    make_sizing(ns_e4, 5.0000, behavior="Soft")
else:
    print("  [WARN] Edge 4 not found at midpoint (-10.00,-10.00,10.00)")

# Edge 7 — Pi_E
edge_7 = find_edge(10.0000, 0.0000, 0.0000)
if edge_7 is not None:
    ns_e7 = make_ns("ISPCC_Edge_7_Pi_E", [edge_7.Id], "Edge")
    make_sizing(ns_e7, 5.0000, behavior="Soft")
else:
    print("  [WARN] Edge 7 not found at midpoint (10.00,0.00,0.00)")

# Edge 10 — Pi_E
edge_10 = find_edge(10.0000, 0.0000, 20.0000)
if edge_10 is not None:
    ns_e10 = make_ns("ISPCC_Edge_10_Pi_E", [edge_10.Id], "Edge")
    make_sizing(ns_e10, 5.0000, behavior="Soft")
else:
    print("  [WARN] Edge 10 not found at midpoint (10.00,0.00,20.00)")

# Edge 11 — Pi_E
edge_11 = find_edge(10.0000, 10.0000, 10.0000)
if edge_11 is not None:
    ns_e11 = make_ns("ISPCC_Edge_11_Pi_E", [edge_11.Id], "Edge")
    make_sizing(ns_e11, 5.0000, behavior="Soft")
else:
    print("  [WARN] Edge 11 not found at midpoint (10.00,10.00,10.00)")

# Edge 12 — Pi_E
edge_12 = find_edge(10.0000, -10.0000, 10.0000)
if edge_12 is not None:
    ns_e12 = make_ns("ISPCC_Edge_12_Pi_E", [edge_12.Id], "Edge")
    make_sizing(ns_e12, 5.0000, behavior="Soft")
else:
    print("  [WARN] Edge 12 not found at midpoint (10.00,-10.00,10.00)")

print("Step 3 done — 8 edge sizing control(s)")

# ════════════════════════════════════════════════════════════════
# Step 4 — Face Sizing: Pi zones, Hard (overrides global)
# Zienkiewicz & Zhu (1987): element size at high-gradient regions
# ════════════════════════════════════════════════════════════════
# Zone 1 — Pi face sizing
if face_z1 is not None:
    ns_fs1 = make_ns("ISPCC_Pi_FaceSizing_1", [face_z1.Id], "Face")
    make_sizing(ns_fs1, 5.0000, behavior="Hard")
    print("  Zone 1 face sizing 5.0000 mm Hard")

# Zone 6 — Pi face sizing
if face_z6 is not None:
    ns_fs6 = make_ns("ISPCC_Pi_FaceSizing_6", [face_z6.Id], "Face")
    make_sizing(ns_fs6, 5.0000, behavior="Hard")
    print("  Zone 6 face sizing 5.0000 mm Hard")

print("Step 4 done — face sizing on 2 Pi face(s)")

# ════════════════════════════════════════════════════════════════
# Step 5 — Sphere of Influence: corner Β entities
# Knupp (2001): Jacobian quality at corner singularities
# h_corner = geometric_mean × 0.5 — halved for corner gradation
# ════════════════════════════════════════════════════════════════
# Corner 1 — Pi_E at (-10.00,-10.00,0.00)
vert_1 = find_vertex(-10.0000, -10.0000, 0.0000)
if vert_1 is not None:
    ns_c1 = make_ns("ISPCC_Corner_1_Pi_E", [vert_1.Id], "Vertex")
    sz_c1 = mesh.AddSizing()
    sz_c1.Location = ns_c1
    sz_c1.Type = SizingType.SphereOfInfluence
    sz_c1.ElementSize = Quantity("2.5000 [mm]")
    sz_c1.SphereRadius = Quantity("5.0000 [mm]")
    print("  Corner 1 sphere h=2.5000 r=5.0000")
else:
    print("  [WARN] Corner 1 vertex not found at (-10.00,-10.00,0.00)")

# Corner 2 — Pi_E at (-10.00,-10.00,20.00)
vert_2 = find_vertex(-10.0000, -10.0000, 20.0000)
if vert_2 is not None:
    ns_c2 = make_ns("ISPCC_Corner_2_Pi_E", [vert_2.Id], "Vertex")
    sz_c2 = mesh.AddSizing()
    sz_c2.Location = ns_c2
    sz_c2.Type = SizingType.SphereOfInfluence
    sz_c2.ElementSize = Quantity("2.5000 [mm]")
    sz_c2.SphereRadius = Quantity("5.0000 [mm]")
    print("  Corner 2 sphere h=2.5000 r=5.0000")
else:
    print("  [WARN] Corner 2 vertex not found at (-10.00,-10.00,20.00)")

# Corner 3 — Pi_E at (-10.00,10.00,0.00)
vert_3 = find_vertex(-10.0000, 10.0000, 0.0000)
if vert_3 is not None:
    ns_c3 = make_ns("ISPCC_Corner_3_Pi_E", [vert_3.Id], "Vertex")
    sz_c3 = mesh.AddSizing()
    sz_c3.Location = ns_c3
    sz_c3.Type = SizingType.SphereOfInfluence
    sz_c3.ElementSize = Quantity("2.5000 [mm]")
    sz_c3.SphereRadius = Quantity("5.0000 [mm]")
    print("  Corner 3 sphere h=2.5000 r=5.0000")
else:
    print("  [WARN] Corner 3 vertex not found at (-10.00,10.00,0.00)")

# Corner 4 — Pi_E at (-10.00,10.00,20.00)
vert_4 = find_vertex(-10.0000, 10.0000, 20.0000)
if vert_4 is not None:
    ns_c4 = make_ns("ISPCC_Corner_4_Pi_E", [vert_4.Id], "Vertex")
    sz_c4 = mesh.AddSizing()
    sz_c4.Location = ns_c4
    sz_c4.Type = SizingType.SphereOfInfluence
    sz_c4.ElementSize = Quantity("2.5000 [mm]")
    sz_c4.SphereRadius = Quantity("5.0000 [mm]")
    print("  Corner 4 sphere h=2.5000 r=5.0000")
else:
    print("  [WARN] Corner 4 vertex not found at (-10.00,10.00,20.00)")

# Corner 5 — Pi_E at (10.00,-10.00,0.00)
vert_5 = find_vertex(10.0000, -10.0000, 0.0000)
if vert_5 is not None:
    ns_c5 = make_ns("ISPCC_Corner_5_Pi_E", [vert_5.Id], "Vertex")
    sz_c5 = mesh.AddSizing()
    sz_c5.Location = ns_c5
    sz_c5.Type = SizingType.SphereOfInfluence
    sz_c5.ElementSize = Quantity("2.5000 [mm]")
    sz_c5.SphereRadius = Quantity("5.0000 [mm]")
    print("  Corner 5 sphere h=2.5000 r=5.0000")
else:
    print("  [WARN] Corner 5 vertex not found at (10.00,-10.00,0.00)")

# Corner 6 — Pi_E at (10.00,-10.00,20.00)
vert_6 = find_vertex(10.0000, -10.0000, 20.0000)
if vert_6 is not None:
    ns_c6 = make_ns("ISPCC_Corner_6_Pi_E", [vert_6.Id], "Vertex")
    sz_c6 = mesh.AddSizing()
    sz_c6.Location = ns_c6
    sz_c6.Type = SizingType.SphereOfInfluence
    sz_c6.ElementSize = Quantity("2.5000 [mm]")
    sz_c6.SphereRadius = Quantity("5.0000 [mm]")
    print("  Corner 6 sphere h=2.5000 r=5.0000")
else:
    print("  [WARN] Corner 6 vertex not found at (10.00,-10.00,20.00)")

# Corner 7 — Pi_E at (10.00,10.00,0.00)
vert_7 = find_vertex(10.0000, 10.0000, 0.0000)
if vert_7 is not None:
    ns_c7 = make_ns("ISPCC_Corner_7_Pi_E", [vert_7.Id], "Vertex")
    sz_c7 = mesh.AddSizing()
    sz_c7.Location = ns_c7
    sz_c7.Type = SizingType.SphereOfInfluence
    sz_c7.ElementSize = Quantity("2.5000 [mm]")
    sz_c7.SphereRadius = Quantity("5.0000 [mm]")
    print("  Corner 7 sphere h=2.5000 r=5.0000")
else:
    print("  [WARN] Corner 7 vertex not found at (10.00,10.00,0.00)")

# Corner 8 — Pi_E at (10.00,10.00,20.00)
vert_8 = find_vertex(10.0000, 10.0000, 20.0000)
if vert_8 is not None:
    ns_c8 = make_ns("ISPCC_Corner_8_Pi_E", [vert_8.Id], "Vertex")
    sz_c8 = mesh.AddSizing()
    sz_c8.Location = ns_c8
    sz_c8.Type = SizingType.SphereOfInfluence
    sz_c8.ElementSize = Quantity("2.5000 [mm]")
    sz_c8.SphereRadius = Quantity("5.0000 [mm]")
    print("  Corner 8 sphere h=2.5000 r=5.0000")
else:
    print("  [WARN] Corner 8 vertex not found at (10.00,10.00,20.00)")

print("Step 5 done — 8 corner sphere(s)")

# ════════════════════════════════════════════════════════════════
# Step 6 — Sphere of Influence: interior B_sphere correction
# Load midpoint — equidistant from both Pi faces.
# Sphere mesh distributes load radially. Planar gradient incorrect.
# Applied to nearest vertex; covers midpoint via SOI radius.
# ════════════════════════════════════════════════════════════════
vert_bsph = find_vertex(0.0000, 0.0000, 10.0000, tol=15.0)
if vert_bsph is not None:
    ns_bsph = make_ns("ISPCC_Interior_BSphere", [vert_bsph.Id], "Vertex")
    sz_bsph = mesh.AddSizing()
    sz_bsph.Location = ns_bsph
    sz_bsph.Type = SizingType.SphereOfInfluence
    sz_bsph.ElementSize = Quantity("2.5000 [mm]")
    sz_bsph.SphereRadius = Quantity("5.0000 [mm]")
    print("Interior B_sphere correction: h=2.5000 r=5.0000")
else:
    print("[WARN] Interior B_sphere vertex not found — check coordinate")

print("Step 6 done — interior B_sphere correction")

# ════════════════════════════════════════════════════════════════
# Generate mesh
# ════════════════════════════════════════════════════════════════
# mesh.GenerateMesh()  # uncomment to generate automatically
# Leave commented for manual review of controls before meshing.
print("All mesh controls applied. Review in outline tree.")
print("Run mesh.GenerateMesh() or use Generate Mesh in the GUI.")

# ═══════════════════════════════════════════════════════════════
# End of ISPCC auto-generated mesh script
# ═══════════════════════════════════════════════════════════════